name: trade-vnpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=2.2.3
  - pytest
  - ta-lib
  - pip:
      - vnpy
      - vnpy_ctastrategy
      - vnpy_ctabacktester
      - vnpy_datamanager
      - vnpy_sqlite
      - vnpy_rqdata
